hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false

ribbon:
  ConnectTimeout: ${RIBBON_CONNECT_TIMEOUT:100000}
  ReadTimeout: ${RIBBON_READ_TIMEOUT:100000}
  eureka:
    enabled: true

eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN:${spring.application.name}}
    homePageUrl: http://${APPLICATION_DOMAIN:${spring.application.name}}/
    statusPageUrl: http://${APPLICATION_DOMAIN:${spring.application.name}}/actuator/info
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:user}:${EUREKA_PASSWORD:12345}@${DISCOVERY_SERVER_URL:localhost:8761}/eureka/
    lease:
      duration: 5

server:
  compression:
    enabled: true
    min-response-size: 250000
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/hal+json