info:
  component: User Service

server:
  port: ${PORT:8771}
  servlet:
    context-path: ${CONTEXT_PATH:/user-api}

logging:
  level:
    com.tln.product.service: DEBUG

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=user&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: localpostgres
    password: localpostgressecret
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: always
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL:localhost:29092}
    topic:
      sendEmailNotification: SEND_EMAIL_NOTIFICATION
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0